import type { ComponentType, CSSProperties } from "react";
import {
  Calendar,
  CalendarCheck,
  Contact,
  CreditCard,
  File,
  FileText,
  Image as ImageIcon,
  LayoutGrid,
  Link as LinkIcon,
  Mail,
  MapPin,
  MessageSquare,
  Music,
  Phone,
  Presentation,
  Sheet,
  Video,
  Wifi,
} from "lucide-react";
import { FaAmazon, FaLinkedin } from "react-icons/fa6";
import {
  SiBitcoin,
  SiBookingdotcom,
  SiEtsy,
  SiFacebook,
  SiGoogle,
  SiGoogledocs,
  SiGoogleforms,
  SiGooglemaps,
  SiGooglesheets,
  SiInstagram,
  SiKakaotalk,
  SiLine,
  SiPaypal,
  SiReddit,
  SiSnapchat,
  SiSpotify,
  SiTelegram,
  SiTiktok,
  SiVenmo,
  SiWechat,
  SiWhatsapp,
  SiX,
  SiYoutube,
} from "react-icons/si";
import type { QrType } from "@/lib/types";

export type QrIcon = ComponentType<{
  className?: string;
  style?: CSSProperties;
  size?: number | string;
}>;

/** Per-type icon. Brand logos use react-icons; generic types use lucide. */
export const QR_TYPE_ICONS: Record<QrType, QrIcon> = {
  url: LinkIcon,
  text: FileText,
  map: SiGooglemaps,
  wifi: Wifi,
  whatsapp: SiWhatsapp,
  phone: Phone,
  sms: MessageSquare,
  email: Mail,
  vcard: Contact,
  calendar: Calendar,
  telegram: SiTelegram,
  wechat: SiWechat,
  line: SiLine,
  kakaotalk: SiKakaotalk,
  tiktok: SiTiktok,
  instagram: SiInstagram,
  facebook: SiFacebook,
  youtube: SiYoutube,
  linkedin: FaLinkedin,
  x: SiX,
  snapchat: SiSnapchat,
  reddit: SiReddit,
  spotify: SiSpotify,
  google_forms: SiGoogleforms,
  google_review: SiGoogle,
  google_docs: SiGoogledocs,
  google_sheets: SiGooglesheets,
  office_365: FileText,
  paypal: SiPaypal,
  venmo: SiVenmo,
  upi: CreditCard,
  crypto_payment: SiBitcoin,
  amazon: FaAmazon,
  etsy: SiEtsy,
  booking: SiBookingdotcom,
  online_booking: CalendarCheck,
  link_hub: LayoutGrid,
  custom_url: LinkIcon,
  pdf: FileText,
  audio: Music,
  video: Video,
  image: ImageIcon,
  pptx: Presentation,
  excel: Sheet,
  png: ImageIcon,
  file: File,
};

/** Brand accent color per type (hex). Used to tint icons. Falls back to slate. */
export const QR_TYPE_COLORS: Partial<Record<QrType, string>> = {
  map: "#34A853",
  whatsapp: "#25D366",
  telegram: "#26A5E4",
  wechat: "#07C160",
  line: "#00C300",
  kakaotalk: "#FFCD00",
  tiktok: "#000000",
  instagram: "#E4405F",
  facebook: "#1877F2",
  youtube: "#FF0000",
  linkedin: "#0A66C2",
  x: "#000000",
  snapchat: "#FFFC00",
  reddit: "#FF4500",
  spotify: "#1DB954",
  google_forms: "#7248B9",
  google_review: "#4285F4",
  google_docs: "#4285F4",
  google_sheets: "#34A853",
  paypal: "#003087",
  venmo: "#008CFF",
  crypto_payment: "#F7931A",
  amazon: "#FF9900",
  etsy: "#F16521",
  booking: "#003580",
};

export function qrTypeIcon(type: QrType): QrIcon {
  return QR_TYPE_ICONS[type] ?? FileText;
}
